<?php
/**------------------------------------------------------------------------
 * SM Search Box - Version 2.0.0
 * Copyright (c) 2015 YouTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * Author: YouTech Company
 * Websites: http://www.magentech.com
 * -------------------------------------------------------------------------*/

if (!$this->_getConfig('isenabled', 1)) return;

/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Sm\SearchBox\Helper\Data */
/** @var $helperSearch \Magento\Search\Helper\Data */

$helperSearch = $this->helper('Magento\Search\Helper\Data');
$helper       = $this->helper('Sm\SearchBox\Helper\Data');
$tag_id       = 'sm_searchbox' . rand() . time();
$cat_list     = $this->getCategories();

$limit_popular = $this->_getConfig('limit_popular');

?>

<div id="<?php echo $tag_id; ?>" class="block block-search search-pro">
    <div class="block block-content">
        <form class="form minisearch" id="searchbox_mini_form" action="<?php /* @escapeNotVerified */
        echo $helperSearch->getResultUrl() ?>" method="get">
            <div class="field search">
                <div class="control">
                    <select class="cat searchbox-cat" name="cat">
                        <option value=""><?php echo __('All Categories') ?></option>
                        <?php foreach ($cat_list as $cat) { ?>
                            <option value="<?php echo $cat['value']; ?>" <?php echo(($this->getRequest()->getParam('cat') && ($this->getRequest()->getParam('cat') == $cat['value'])) ? "selected" : ''); ?> ><?php echo $cat['label']; ?></option>
                        <?php } ?>
                    </select>

                    <input id="searchbox"
                           data-mage-init='{"quickSearch":{
									"formSelector":"#searchbox_mini_form",
									"url":"<?php /* @escapeNotVerified */
                           echo $block->getUrl('search/ajax/suggest'); ?>",
									"destinationSelector":"#searchbox_autocomplete"}
							   }'
                           type="text"
                           name="<?php /* @escapeNotVerified */
                           echo $helperSearch->getQueryParamName() ?>"
                           placeholder="<?php echo __('Enter keywords to search...') ?>"
                           class="input-text input-searchbox"
                           maxlength="<?php /* @escapeNotVerified */
                           echo $helperSearch->getMaxQueryLength(); ?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-expanded="true"
                           aria-autocomplete="both"
                           autocomplete="off"/>
                    <div id="searchbox_autocomplete" class="search-autocomplete"></div>
                    <?php echo $block->getChildHtml() ?>

                </div>
            </div>
            <div class="actions">
                <button type="submit" title="<?php echo $block->escapeHtml(__('Search')) ?>" class="btn-searchbox">
						<span><?php /* @escapeNotVerified */
                            echo __('Search'); ?></span>
                </button>
            </div>
        </form>
    </div>
</div>