<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<li class="post-holder col-sm-6 post-holder-<?php echo $_post->getId() ?>">
    <div class="post-content post-custom">
        <div class="post-description clearfix">
            <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
            <div class="post-ftimg-hld">
                <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                    <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
                </a>
            </div>
            <?php } ?>
			
			<div class="post-info-blog">
				<div class="post-header">
				

					<?php echo $this->getInfoHtml() ?>
					<h2 class="post-title">
							<a class="post-item-link"
							   href="<?php echo $_postUrl ?>">
								<?php echo $_postName; ?>
							</a>
					</h2>
				</div>
				
				<div class="post-text-hld clearfix">
					<?php echo $block->getShorContent() ?>
				</div>
				<a class="post-read-more text-theme-color" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>"
				   >
				   <?php echo __('Read more') ?>
				</a>
			</div>

        </div>
    </div>
    <div class="post-footer">

    </div>
</li>