<?php
/**
 * Copyright © 2016 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list toolbar template
 *
 * @var $block \Magefan\Blog\Block\Post\PostList\Toolbar
 */
$limit    = $this->helper('Magefan\Blog\Helper\Data')->getConfig('mfblog/post_list/posts_per_page');
$sizeItem = $block->getCollection()->getSize();
?>
<?php if ($sizeItem && $sizeItem > $limit) { ?>
    <?php $woj = $block->getWidgetOptionsJson() ?>
    <div class="toolbar toolbar-blog-posts clearfix" <?php if ($woj) echo 'data-mage-init="' . $woj . '"' ?>>
        <?php echo $block->getPagerHtml() ?>
    </div>
<?php } ?>
